FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Install MyPy
RUN pip install mypy

# Copy the rest of your application code
COPY . .

# Run MyPy to check types
RUN mypy .

# Command to run your application
CMD ["python", "test.py"]
